<a href="https://colab.research.google.com/github/ramvrum/dap-2024/blob/main/les04/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №4.
# Анализ данных пассажиров "Титаника"

Гибель Титаника – одно из самых печально известных кораблекрушений в истории.

15 апреля 1912 года во время своего первого плавания считавшийся «непотопляемым» «Титаник» затонул после столкновения с айсбергом.
К сожалению, спасательных шлюпок для всех находившихся на борту не хватило, в результате чего погибли 1502 из 2224 пассажиров и членов экипажа.

Используя набор данных titanic.csv выполните следующие 10 заданий.

In [ ]:
import numpy as np
import pandas as pd

1. Создайте DataFarame из файла titanic.csv, в качестве индекса используйте столбец "PassengerId"

In [3]:
import pandas as pd

link = "https://raw.githubusercontent.com/ramvrum/dap-2024/main/les04/data/titanic.csv"
df = pd.read_csv(link, index_col="PassengerId")

df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

2. Просмотрите первые 6 строк

In [5]:
df.head(6)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

3. Выведите описание данных

In [6]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

4. Сколько мужчин / женщин находилось на борту?

In [7]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

4. Выведите распределение переменной Pclass (социально-экономический статус) и это же распределение, только для мужчин / женщин по отдельности. Сколько было мужчин 2-го класса

In [9]:
print("Общее распределение:")
print(df['Pclass'].value_counts())

print("Для мужчин:")
print(df[df['Sex'] == 'male']['Pclass'].value_counts())
print("Для женщин:")
print(df[df['Sex'] == 'female']['Pclass'].value_counts())

male_class2 = df[(df['Sex'] == 'male') & (df['Pclass'] == 2)].shape[0]
print("Мужчин 2-го класса:", male_class2)

Общее распределение:
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Для мужчин:
Pclass
3    347
1    122
2    108
Name: count, dtype: int64
Для женщин:
Pclass
3    144
1     94
2     76
Name: count, dtype: int64
Мужчин 2-го класса: 108

5. Каковы медиана и среднеквадрати́чное отклонение платежей (Fare)? Округлите до 2 десятичных знаков.

In [10]:
median = round(df['Fare'].median(), 2)
std = round(df['Fare'].std(), 2)

median, std

(14.45, 49.69)

6. Правда ли, что люди моложе 30 лет выживали чаще, чем люди старше 60 лет? Каковы доли выживших в обеих группах?

In [12]:
young = df[df['Age'] < 30]
young_ratio = round(young['Survived'].mean(), 2)

old = df[df['Age'] > 60]
old_ratio = round(old['Survived'].mean(), 2)

print("Моложе 30: ", young_ratio)
print("Старше 60: ", old_ratio)

Моложе 30:  0.41
Старше 60:  0.23

7. Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших в обеих группах?

In [13]:
female = df[df['Sex'] == 'female']
female_ratio = round(female['Survived'].mean(), 2)

male = df[df['Sex'] == 'male']
male_ratio = round(male['Survived'].mean(), 2)

print("Женщины: ", female_ratio)
print("Мужчины: ", male_ratio)

Женщины:  0.74
Мужчины:  0.19

8.  Найдите самое популярное имя среди пассажиров Титаника мужского пола?

In [19]:
male = df[df['Sex'] == 'male']

first_names = male['Name'].str.extract(r',\s*[^.]*\.\s*(\w+)')[0]

common_name = first_names.mode()[0]
common_name

'William'



9. Как отличается средний возраст мужчин / женщин в зависимости от класса обслуживания? Выберите верные утверждения:

    В среднем мужчины 1-го класса старше 40 лет (верно)

    В среднем женщины 1-го класса старше 40 лет (ложь)

    Мужчины всех классов в среднем старше женщин того же класса (верно)

    В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса (верно)

In [21]:
ages = df.groupby(['Pclass', 'Sex'])['Age'].mean()
ages

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

10. Сравните возраст у спасенных и у погибших пасажиров. Средний возраст погибших выше, верно? (верно)

In [23]:
df.groupby('Survived')['Age'].mean().rename(index={0: 'Погибшие', 1: 'Выжившие'})

Survived
Погибшие    30.626179
Выжившие    28.343690
Name: Age, dtype: float64

### Дополнительные вопросы для защиты

1. Что такое медиана? Рассчитать медиану для предложенного ряда чисел.

Медиана — это число, которое делит ряд данных на две равные части.
Пример для ряда [1, 3, 2, 5, 4]:


```
import numpy as np
data = [1, 3, 2, 5, 4]
np.median(data)  # 3
```

2. Что такое дисперсия? Рассчитать дисперсию для предложенного ряда чисел.

Дисперсия — это мера разброса данных относительно среднего.

Если дисперсия большая → числа сильно разбросаны.

Если дисперсия маленькая → числа близки к среднему.

```
import numpy as np
data = [1, 3, 2, 5, 4]
np.var(data) #2.0
```

3. Что такое среднеквадратичное отклонение? Рассчитать среднеквадратичное отклонение для предложенного ряда чисел.

Это квадратный корень из дисперсии, показывает среднее отклонение элементов от среднего.

```
np.std(data)  # 1.414...
```

4. Что такое Series и чем он отличается от DataFrame

Series — одномерный массив с индексами.
DataFrame — двумерная таблица (строки и столбцы).

5. Можно ли изменить индекс в Series после создания объекта?

Да, можно.

6. Можно ли выполнить операцию сложения над двумя объектами Series, если они имеют:
- одинаковые типы данных, одинаковые размеры и одинаковые индексы? Да
- одинаковые типы данных, одинаковые размеры, но разные индексы? Да, но результат содержит NaN для несоответствующих индексов  
- одинаковые типы данных, разные размеры и одинаковые индексы? Нет
- разные типы данных, одинаковые размеры и одинаковые индексы? Да
- разные типы данных, одинаковые размеры и разные индексы? Да, но будут NaN для несоответствующих индексов
- разные типы данных, разные размеры и разные индексы? Нет
7. Что такое DataFrame и чем он отличается от Series

DataFrame — таблица с несколькими столбцами (каждый столбец может быть Series).
Series — один столбец/вектор данных.

8. Что необходимо сделать, чтобы число строк в DateFrame при его просмотре, по умолчанию составляло 8?


```
pd.set_option('display.max_rows', 8)
```


9. Чем отличается метод iloc от метода loс

iloc — обращение по позициям (числовые индексы)

loc — обращение по меткам (индексы/имена строк)

10. Можно ли добавить в DateFrame дополнительный Series?

Да, можно.

11. Требуются ли установка дополнительных библиотек для загрузки с помощью pandas файлов в формате CSV? Excel (.xls)? Json?

CSV — не требуется, pandas умеет сразу

Excel (.xls/.xlsx) — требуется openpyxl или xlrd

JSON — не требуется, pandas умеет читать .json